[package]
name = "problems"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = 'crystal_balls'
path = './src/crystal_balls.rs'

[dependencies]
